env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:jest/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-redux/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - jest
  - react
  - react-redux
rules:
  no-extra-boolean-cast: off
  no-empty: off
  no-case-declarations: off
  no-unused-vars:
    - error
    - varsIgnorePattern: '_.+'
      argsIgnorePattern: '_.*|reject'
  react/no-unescaped-entities: off
  react/display-name: off
  react/prop-types: off
  react-redux/prefer-separate-component-file: off
  jest/no-disabled-tests: off
  no-redeclare:
    - 'error'
    - builtinGlobals: false
settings:
  react:
    version: detect
