* Changelog

All notable changes to this project will be documented in this file.

** <2019-08-25 Sun>

*** Added

Since we want Organ to be a community driven project, we have added:
  -  [[file:CODE_OF_CONDUCT.org][Code of conduct]]
  -  [[file:CONTRIBUTING.org][Contributing guidelines]]

** <2019-08-12 Mon>

*** Changed

- The default keybindings (when used from a desktop browser) are now
  more in line with the defaults in Emacs itself

*** Fixed

- The keybindings work on non-macOS operating systems

** <2019-08-10 Sat>

*** Added

- As a user, when in a directory listing, I want the folders and files
  to be sorted alphabetically. Furthermore, I only want to see files
  that org-web can open (that is org and org archive files).
- Note: This is only implemented for the Dropbox back-end at this time.

*** Changed

- Filters files from a directory listing down to org files.
- Sorts folders atop of files.
- Sorts both folders and files alphabetically.


** <2019-08-05 Mon>

*** Added

- When the browser tab becomes visible, pull the latest version of the
  Org file
  - This is rather helpful when the app is used in production. Since
    the production build supports loading the complete application and
    org-file from cache, it can be open for a very long time. When the
    org-file hasn't been pulled in a "very long time"™, then chances
    are non-nil that the file has been changed by another client in
    the meantime.
  - Without this change, when the user opens the app after a while,
    makes changes to the file and wants to sync to the back-end, there
    might be the message "Since you last pulled, a newer version of
    the file has been pushed to the server.". Now the user has two
    conflicting versions of the same file and can only chose to keep
    one (Which in itself is great UX and great error handling for
    cases in which we do encounter a merge conflict, of course!).
  - This situation is mitigated with this change. Now the user has the
    option to enable "Sync on application becoming visible" which acts
    similarly to "Live Sync". When the user opts to use this feature,
    whenever the application get's pulled from the background or
    started through the service worker, the first thing that happens
    it that a new version of the org-file is pulled from the server.
    It's therefore much harder for the user to create conflicts.

** <2019-08-04 Sun>

*** Fixed

- Parser doesn't break indentation of existing files in fewer places
- Planning Items are formatted as in Emacs Org mode
- Properties are formatted as in Emacs Org mode
- Tags are formatted as in Emacs Org mode


** <2019-08-03 Sat>

*** Added

- Documented deployment options
  - People have been asking for tighter access restrictions.
  - Imo the best answer to that request is to make it as easy as
    possible to host org-web.
  - There's myriads of good options, of course. I picked to document
    two that will (potentially) be cost-free to the users and which
    are very easy and quick to set up: Ftp and Heroku.

*** Fixed

- Tests on =master= were red
  - Partly due to obsolete tests
  - Partly because tests weren't updated according to changes in the code
